name: build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
        with:
          context: ckan-2.10
          file: Dockerfile.py3.10
          build-args: |
            CKAN_REF=ckan-2.10.5
            ENV=base
          tags: |
            ckan/ckan-base:2.10-py3.10
            ckan/ckan-base:2.10.5-py3.10
      
#      - name: Test
#        run: |
#          docker run --rm ${{ env.TEST_TAG }}          
