name: build

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      solr:
        image: ckan/ckan-solr:2.10-solr9
        ports:
          - 8983:8983
      postgres:
        image: ckan/ckan-postgres-dev:2.10
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:7
          ports:
            - 6379:6379

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          context: "{{defaultContext}}:ckan-2.10"
          file: Dockerfile.py3.10
          build-args: |
            CKAN_REF=ckan-2.10.5
            ENV=base
          tags: |
            ckan/ckan-base:2.10-py3.10

      - name: Test base image
        run: |
          docker run \
            --rm \
            --net=host \
            -e CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@localhost/ckan_test \
            -e CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@localhost/datastore_test \
            -e CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@localhost/datastore_test \
            -e CKAN_SOLR_URL=http://localhost:8983/solr/ckan \
            -e CKAN_REDIS_URL=redis://localhost:6379/1 \
            -e CKAN_INI=/srv/app/src/ckan/test-core.ini \
            --entrypoint "" \
            ckan/ckan-base:2.10-py3.10 \
            ckan --help

      - name: Build dev image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          context: "{{defaultContext}}:ckan-2.10"
          file: Dockerfile.py3.10
          build-args: |
            CKAN_REF=ckan-2.10.5
            ENV=dev
          tags: |
            ckan/ckan-dev:2.10-py3.10

      - name: Test dev image
        run: |
          docker run \
            --rm \
            --net=host \
            -e CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@localhost/ckan_test \
            -e CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@localhost/datastore_test \
            -e CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@localhost/datastore_test \
            -e CKAN_SOLR_URL=http://localhost:8983/solr/ckan \
            -e CKAN_REDIS_URL=redis://localhost:6379/1 \
            -e CKAN_INI=/srv/app/src/ckan/test-core.ini \
            --entrypoint "" \
            ckan/ckan-dev:2.10-py3.10 \
            pytest --ckan-ini=/srv/app/src/ckan/test-core.ini -v /srv/app/src/ckan/ckan/tests/logic/action/test_create.py::TestDatasetCreate
