name: Build and test CKAN 2.10 images (alpine)

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      ckan-major-version: "2.10"
      base-tag: "ckan/ckan-base:2.10"
      dev-tag: "ckan/ckan-dev:2.10"
