name: Build and test CKAN 2.11 images

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      ckan-major-version: "2.11"
      base-tag: "ckan/ckan-base:2.11"
      dev-tag: "ckan/ckan-dev:2.11"
