name: Build and test CKAN 2.11 images (python 3.11)

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      ckan-major-version: "2.11"
      python-version: "3.11"
