name: Build and test CKAN 2.9 images (python)

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      ckan-major-version: "2.9"
      docker-file: "Dockerfile.py3.9"
