name: Build and publish the master docker-ckan image
on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ckan-base master
        uses: docker/build-push-action@v6
        with:
          context: ckan-master/base
          file: ckan-master/base/Dockerfile
          push: true
          build-args: |
            CKAN_VERSION=master
          tags: |
            ckan/ckan-base:master
      - name: Build ckan-dev master
        uses: docker/build-push-action@v6
        with:
          context: ckan-master/dev
          file: ckan-master/dev/Dockerfile
          push: true
          build-args: |
            CKAN_VERSION=master
          tags: |
            ckan/ckan-dev:master
